FROM arm64v8/node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN apk add --no-cache git \
    && npm ci \
    && npm cache clean --force

COPY . .

ARG NEXT_PUBLIC_FIREBASE_MEASUREMENTID
ARG NEXT_PUBLIC_FIREBASE_APPID
ARG NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID
ARG NEXT_PUBLIC_FIREBASE_STORAGEBUCKET
ARG NEXT_PUBLIC_FIREBASE_PROJECTID
ARG NEXT_PUBLIC_FIREBASE_AUTHDOMAIN
ARG NEXT_PUBLIC_FIREBASE_APIKEY
ARG NEXT_PUBLIC_IMAGES_RAW_URL
ARG NEXT_PUBLIC_IMAGES_W500_URL
ARG NEXT_PUBLIC_IMAGES_W400_URL
ARG NEXT_PUBLIC_IMAGES_W300_URL
ARG NEXT_PUBLIC_IMAGES_W200_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_ANALYTICS_ID
ARG NEXT_PUBLIC_URL_LINK_CV

ENV NEXT_PUBLIC_FIREBASE_MEASUREMENTID=$NEXT_PUBLIC_FIREBASE_MEASUREMENTID \
    NEXT_PUBLIC_FIREBASE_APPID=$NEXT_PUBLIC_FIREBASE_APPID \
    NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID=$NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID \
    NEXT_PUBLIC_FIREBASE_STORAGEBUCKET=$NEXT_PUBLIC_FIREBASE_STORAGEBUCKET \
    NEXT_PUBLIC_FIREBASE_PROJECTID=$NEXT_PUBLIC_FIREBASE_PROJECTID \
    NEXT_PUBLIC_FIREBASE_AUTHDOMAIN=$NEXT_PUBLIC_FIREBASE_AUTHDOMAIN \
    NEXT_PUBLIC_FIREBASE_APIKEY=$NEXT_PUBLIC_FIREBASE_APIKEY \
    NEXT_PUBLIC_IMAGES_RAW_URL=$NEXT_PUBLIC_IMAGES_RAW_URL \
    NEXT_PUBLIC_IMAGES_W500_URL=$NEXT_PUBLIC_IMAGES_W500_URL \
    NEXT_PUBLIC_IMAGES_W400_URL=$NEXT_PUBLIC_IMAGES_W400_URL \
    NEXT_PUBLIC_IMAGES_W300_URL=$NEXT_PUBLIC_IMAGES_W300_URL \
    NEXT_PUBLIC_IMAGES_W200_URL=$NEXT_PUBLIC_IMAGES_W200_URL \
    NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
    NEXT_PUBLIC_ANALYTICS_ID=$NEXT_PUBLIC_ANALYTICS_ID \
    NEXT_PUBLIC_URL_LINK_CV=$NEXT_PUBLIC_URL_LINK_CV

RUN npm run build

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

CMD ["npm", "run", "start"]
